export { useApiClient } from './use-api-client';
export {
  // Plants
  usePlants,
  usePlant,
  useCreatePlant,
  useMovePlant,
  useTransitionPlantStage,
  usePlantStageHistory,
  // Batches
  useBatches,
  useBatch,
  useCreateBatch,
  useHarvestBatch,
  useBatchHarvests,
  // Strains
  useStrains,
  useStrain,
  useCreateStrain,
  useUpdateStrain,
  useDeactivateStrain,
  // Change Controls
  useChangeControls,
  useChangeControl,
  useCreateChangeControl,
  useSubmitChangeControl,
  useAssessImpact,
  useApproveChangeControl,
  useRejectChangeControl,
  useVerifyChangeControl,
  useCloseChangeControl,
  // CAPAs
  useCAPAs,
  useCAPA,
  useCreateCAPA,
  useInitiateRca,
  useCreateActionPlan,
  useCheckEffectiveness,
  useCloseCAPA,
  // Deviations
  useDeviations,
  useDeviation,
  useReportDeviation,
  useInvestigateDeviation,
  useAssessDeviationImpact,
  useLinkCapaToDeviation,
  useCloseDeviation,
  // Validation Protocols
  useValidationProtocols,
  useValidationProtocol,
  useValidationProtocolSummary,
  useCreateValidationProtocol,
  useApproveValidationProtocol,
  useExecuteValidationTest,
  useCloseValidationProtocol,
  // Quality Events
  useQualityEvents,
  useQualityEvent,
  useCreateQualityEvent,
  useInvestigateQualityEvent,
  useLinkRecordToQualityEvent,
  useCloseQualityEvent,
  // Other
  useAccounts,
  useAccount,
  useCreateAccount,
  useJournalEntries,
  useJournalEntry,
  useCreateJournalEntry,
  usePostJournalEntry,
  useReverseJournalEntry,
  useLatestBiologicalAssetValuation,
  useRecordBiologicalAssetValuation,
  // Procurement
  useSuppliers,
  useSupplier,
  useCreateSupplier,
  useQualifySupplier,
  usePurchaseOrders,
  usePurchaseOrder,
  useCreatePurchaseOrder,
  useSubmitPurchaseOrder,
  useAcknowledgePurchaseOrder,
  useReceiveGoods,
  useClosePurchaseOrder,
  useCancelPurchaseOrder,
  // Spatial
  useZones,
  useZone,
  useCreateZone,
  useActiveAssignments,
  useAssignBatchToZone,
  useBatchAssignment,
  useReleaseBatchFromZone,
  // Workforce
  useEmployees,
  useEmployee,
  useCreateEmployee,
  useDeactivateEmployee,
  useEmployeeCompetency,
  useTasks,
  useTask,
  useCreateTask,
  useCompleteTask,
  useAssignTask,
  useTimeEntries,
  useCreateTimeEntry,
  useClockOut,
  useApproveTimeEntry,
  // Training
  useCourses,
  useCourse,
  useCreateCourse,
  useTrainingExecutions,
  useCreateTrainingExecution,
  useCompleteTrainingExecution,
  useCertifications,
  // Analytics
  useKpis,
  useTrainingCompliance,
  useWorkforceSummary,
  useAuditReadiness,
  useAuditTrail,
  // IoT
  useZoneReadings,
  useIotAlerts,
  // Documents
  useDocuments,
  useDocument,
  useDocumentVersions,
  useCreateDocument,
  useUploadVersion,
  useSubmitForReview,
  useApproveDocument,
  // Facilities (Cultivation Spatial Hierarchy)
  useFacilities,
  useFacility,
  useCreateFacility,
  useUpdateFacility,
  // Buildings
  useBuildings,
  useBuilding,
  useCreateBuilding,
  useUpdateBuilding,
  // Rooms (under buildings)
  useBuildingRooms,
  useCreateRoom,
  useRoom,
  useUpdateRoom,
  // Zones (under rooms)
  useRoomZones,
  useCreateCultivationZone,
  useCultivationZone,
  useUpdateCultivationZone,
} from './use-domain-queries';
